# Generated by Django 5.0.2 on 2024-02-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_phone_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='=', max_length=255),
            preserve_default=False,
        ),
    ]
